Repository Naitik-Jain/October-2022, pull requests merged in 2022-10, with the labels that each got.

#1 Update Swap
  Swap
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST

#2 Update Split
  Split
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#8 Update Sort 1 to N by swapping adjacent elements.cpp
  Sort 1 to N by swapping adjacent elements.cpp
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, hacktoberfest2022

#9 Update Sort a nearly sorted (or K sorted) array.cpp
  Sort a nearly sorted (or K sorted) array.cpp
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, hacktoberfest2022

#11 Update reversal algorithm of array rotation.cpp
  reversal algorithm of array rotation.cpp
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, hacktoberfest2022
